export const causes = [
  { name: "Aapi led", value: "aapi-led" },
  { name: "Adoption", value: "adoption" },
  { name: "Afghanistan", value: "afghanistan" },
  { name: "Animals", value: "animals" },
  { name: "Athletics", value: "athletics" },
  { name: "Autism", value: "autism" },
  { name: "Black led", value: "black-led" },
  { name: "Cancer", value: "cancer" },
  { name: "Cats", value: "cats" },
  { name: "Climate", value: "climate" },
  { name: "Conservation", value: "conservation" },
  { name: "Coronavirus", value: "coronavirus" },
  { name: "Culture", value: "culture" },
  { name: "Dance", value: "dance" },
  { name: "Disabilities", value: "disabilities" },
  { name: "Disease", value: "disease" },
  { name: "Dogs", value: "dogs" },
  { name: "Education", value: "education" },
  { name: "Environment", value: "environment" },
  { name: "Food security", value: "food-security" },
  { name: "Free press", value: "freepress" },
  { name: "Gender equality", value: "gender-equality" },
  { name: "Health", value: "health" },
  { name: "Housing", value: "housing" },
  { name: "Humans", value: "humans" },
  { name: "Hurricane laura", value: "hurricane-laura" },
  { name: "Immigrants", value: "immigrants" },
  { name: "Indigenous led", value: "indigenous-led" },
  { name: "Indigenous peoples", value: "indigenous-peoples" },
  { name: "Justice", value: "justice" },
  { name: "Latine led", value: "latine-led" },
  { name: "Legal", value: "legal" },
  { name: "Libraries", value: "libraries" },
  { name: "Mental health", value: "mental-health" },
  { name: "Middle east", value: "middle-east" },
  { name: "Museums", value: "museums" },
  { name: "Music", value: "music" },
  { name: "Oceans", value: "oceans" },
  { name: "Poverty", value: "poverty" },
  { name: "Racial justice", value: "racial-justice" },
  { name: "Refugees", value: "refugees" },
  { name: "Research", value: "research" },
  { name: "Science", value: "science" },
  { name: "Seniors", value: "seniors" },
  { name: "Space", value: "space" },
  { name: "Theater", value: "theater" },
  { name: "Ukraine", value: "ukraine" },
  { name: "Veterans", value: "veterans" },
  { name: "Visual art", value: "visualart" },
  { name: "Voting rights", value: "votingrights" },
  { name: "Water", value: "water" },
  { name: "Wildfires", value: "wildfires" },
  { name: "Wildlife", value: "wildlife" },
  { name: "Women led", value: "women-led" },
  { name: "Womens health", value: "womens-health" },
  { name: "Youth", value: "youth" },
];
